name: push
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Specify node version...
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      - name: Set Up Environment Variables
        run: cp .env.default .env
      - name: Install Dependencies
        run: yarn install
      - name: Generate typings...
        run: yarn typechain
      - name: Transpile...
        run: yarn transpile:dist:latest
      - name: Run tests...
        run: yarn test --no-compile
      - name: Run coverage...
        run: yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2


